# Generated by Django 4.1.2 on 2022-10-14 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_theme_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='author',
        ),
        migrations.AddField(
            model_name='theme',
            name='authors',
            field=models.ManyToManyField(related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.theme'),
        ),
    ]
