# Generated by Django 4.1.2 on 2022-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_authors_theme_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
