# Generated by Django 4.1.2 on 2023-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hash_link',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
